CC=csc
FLAG=/unsafe
FILES= \
	V3.cs Objet.cs Lampe.cs Couleur.cs Texture.cs MySphere.cs MyRectangle.cs \
	Ecran.cs Program.cs Form1.cs ProjetEleve.cs Form1.Designer.cs \
	Trigo_InvertCoordSpherique.cs

all:
	${CC}  ${FILES} ${FLAG}
